# global settings
set -s set-clipboard on
set -g mouse on
set -g allow-passthrough on

# mode settings
set-window-option -g mode-keys emacs
set-window-option -g xterm-keys on

# key bindings
unbind C-b
set -g prefix C-o
bind C-o send-prefix

bind-key C-y paste-buffer
bind-key -T copy-mode-emacs C-Space send-keys -X begin-selection
bind-key -T copy-mode-emacs M-w send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-emacs MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "tmux load-buffer -w -"
